import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author INFINIX
 */
public class Soal1 extends javax.swing.JFrame {

    /**
     * Creates new form Soal1
     */
    public Soal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNo = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        lbGenre = new javax.swing.JLabel();
        lbJudul = new javax.swing.JLabel();
        cbJudulBuku = new javax.swing.JComboBox<>();
        tfNo = new javax.swing.JTextField();
        tfKode = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        lbKode = new javax.swing.JLabel();
        tfGenre = new javax.swing.JTextField();
        lbPenulis = new javax.swing.JLabel();
        tfPenulis = new javax.swing.JTextField();
        btPinjam = new javax.swing.JButton();
        btKembali = new javax.swing.JButton();
        lbPenerbit = new javax.swing.JLabel();
        tfPenerbit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERPUSTAKAAN");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);
        jPanel1.add(jLabel3, java.awt.BorderLayout.LINE_START);
        jPanel1.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lbNo.setText("No.Registrasi");

        lbNama.setText("Nama");

        lbGenre.setText("Genre");

        lbJudul.setText("Judul Buku");

        cbJudulBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Buku", "Harry Potter", "Percy Jackson And The Olympians", "Diary Of A Murderer", "Private Bodyguard", "Malioboro at Midnight", "Jendral Jevano", " " }));
        cbJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJudulBukuActionPerformed(evt);
            }
        });

        lbKode.setText("Kode Buku");

        lbPenulis.setText("Penulis");

        btPinjam.setText("Meminjam");
        btPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPinjamActionPerformed(evt);
            }
        });

        btKembali.setText("Kembalikan");
        btKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKembaliActionPerformed(evt);
            }
        });

        lbPenerbit.setText("Penerbit");

        tfPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPenerbitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPinjam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btKembali)
                .addGap(13, 13, 13))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNo)
                    .addComponent(lbNama)
                    .addComponent(lbJudul)
                    .addComponent(lbKode)
                    .addComponent(lbGenre)
                    .addComponent(lbPenulis)
                    .addComponent(lbPenerbit))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbJudulBuku, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfKode)
                    .addComponent(tfNama)
                    .addComponent(tfNo)
                    .addComponent(tfGenre)
                    .addComponent(tfPenulis)
                    .addComponent(tfPenerbit))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNo)
                    .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNama)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPenulis)
                    .addComponent(tfPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPenerbit)
                    .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPinjam)
                    .addComponent(btKembali)))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJudulBukuActionPerformed
        String judul = cbJudulBuku.getSelectedItem().toString();
        
        switch (judul) {
            case "Harry Potter" -> {
                tfKode.setText("007");
                tfPenulis.setText("J.K. Rowling");
                tfPenerbit.setText("Gramedia Pustaka Utama");
                tfGenre.setText("Fantasi");
            }
            case "Percy Jackson And The Olympians" -> {
                tfKode.setText("010");
                tfPenulis.setText("Rick Riordan");
                tfPenerbit.setText("Mizan");
                tfGenre.setText("Fantasi, Mitologi");
            }
            case "Diary Of A Murderer" -> {
                tfKode.setText("003");
                tfPenulis.setText("Kim Young Ha");
                tfPenerbit.setText("Gramedia Pustaka Utama");
                tfGenre.setText("Thriller");
            }
            case "Private Bodyguard" -> {
                tfKode.setText("066");
                tfPenulis.setText("Caroline Puspojudo");
                tfPenerbit.setText("Akad");
                tfGenre.setText("Family");
            }
            case "Malioboro at Midnight" -> {
                tfKode.setText("023");
                tfPenulis.setText("Skysphire");
                tfPenerbit.setText("Bukune");
                tfGenre.setText("Romansa Percintaan");
            }
            case "Kamar No 7" -> {
                tfKode.setText("008");
                tfPenulis.setText("Hazzahrra");
                tfPenerbit.setText("Media Kita");
                tfGenre.setText("Horor, Komedi");
            }
            default -> {
                tfKode.setText("-");
            }
        }
        
    }//GEN-LAST:event_cbJudulBukuActionPerformed

    private void btPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPinjamActionPerformed
       String nama = tfNama.getText();
       String no = tfNo.getText();
       String judul = (String) cbJudulBuku.getSelectedItem();
       String kode = tfKode.getText();
       String genre = tfGenre.getText();
       String penulis = tfPenulis.getText();
       String penerbit = tfPenerbit.getText();
       
       if (nama.isEmpty() || no.isEmpty() || judul.isEmpty() || kode.isEmpty() ||
        genre.isEmpty() || penulis.isEmpty() || penerbit.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap isi semua field terlebih dahulu.");
       } else {
       JOptionPane.showConfirmDialog(this, "TELAH MEMINJAM BUKU" + "\n \n No.Registrasi : " + no + 
               "\n \n Nama : "  + nama + "\n \n Kode Buku : " + kode + "\n \n Judul Buku : " + judul + 
               "\n \n Genre : " + genre + "\n \n Penulis : " + penulis  + "\n \n Penerbit : " + penerbit);
       
        tfNama.setText("");
        tfNo.setText("");
        cbJudulBuku.setSelectedIndex(0);
        tfKode.setText("");
        tfGenre.setText("");
        tfPenulis.setText("");
        tfPenerbit.setText("");
       }
    }//GEN-LAST:event_btPinjamActionPerformed

    private void tfPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPenerbitActionPerformed

    private void btKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembaliActionPerformed
       String nama = tfNama.getText();
       String no = tfNo.getText();
       String judul = (String) cbJudulBuku.getSelectedItem();
       String kode = tfKode.getText();
       String genre = tfGenre.getText();
       String penulis = tfPenulis.getText();
       String penerbit = tfPenerbit.getText();
       
       
       JOptionPane.showConfirmDialog(this, "TELAH MEMINJAM BUKU" + "\n \n No.Registrasi : " + no + 
            "\n \n Nama : " + nama + "\n \n Kode Buku : " + kode + "\n \n Judul Buku : " + judul + 
            "\n \n Genre : " + genre + "\n \n Penulis : " + penulis  + "\n \n Penerbit : " + penerbit);
       
        tfNama.setText("");
        tfNo.setText("");
        cbJudulBuku.setSelectedIndex(0);
        tfKode.setText("");
        tfGenre.setText("");
        tfPenulis.setText("");
        tfPenerbit.setText("");
    }//GEN-LAST:event_btKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKembali;
    private javax.swing.JButton btPinjam;
    private javax.swing.JComboBox<String> cbJudulBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbGenre;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbKode;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNo;
    private javax.swing.JLabel lbPenerbit;
    private javax.swing.JLabel lbPenulis;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfPenerbit;
    private javax.swing.JTextField tfPenulis;
    // End of variables declaration//GEN-END:variables
}
